Update updater

diff --git a/scripts/updater b/scripts/updater
--- a/scripts/updater
+++ b/scripts/updater
@@ -107,11 +107,10 @@ function performupdate() {
     OLD_UPDATE="$(git rev-parse HEAD:scripts/updater || echo invalid)"
 
     if [ "$update_channel" == "stable" ]; then
-        git fetch --force --depth 1 origin refs/tags/stable:refs/tags/stable && git reset --hard stable || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 && git reset --hard @{upstream} || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. https://cathook.club\n\033[0m"; exit 1; } }
-    elif [ "$update_channel" == "master" ]; then
-        git fetch --force --depth 1 origin && git reset --hard origin/master || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 && git reset --hard @{upstream} || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. https://cathook.club\n\033[0m"; exit 1; } }
+        git fetch --force --depth 1 origin && git reset --hard origin/master
+ git fetch --force --depth 1 origin || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. https://github.com/ARandomlyGeneratedUsername/hook\n\033[0m"; exit 1; } }
     elif [ "$update_channel" == "developer" ]; then
-        echo -e "\033[1;33m\nWarning! Running in developer mode! Expect issues!\n\033[0m" && git pull origin --rebase=false || { echo -e "\033[1;31m\n\nFailed to pull from github!\n\033[0m"; exit 1; }
+        echo -e "\033[1;33mRunning in developer mode!\n\033[0m" && git pull origin --rebase=false || { echo -e "\033[1;31m\n\nFailed to pull from github!\n\033[0m"; exit 1; }
     else
         if [ "$dialog" == true ]; then
             value=true
@@ -131,12 +130,6 @@ function performupdate() {
     
     NEW_UPDATE=$(git rev-parse HEAD:scripts/updater)
 
-    # Check if the updater script hash has changed. If yes, re-execute yourself (this automates the "double updates" that are sometimes required
-    if [ "$OLD_UPDATE" != "$NEW_UPDATE" ]; then
-        echo -e "\033[1;33m\nWarning: Update script self update!\n\033[0m"
-        CH_UPDATER_SELFUPDATE=1 exec $0 $@
-    fi
-
     # Check if all required packages are installed
     ./scripts/dependencycheck
     
@@ -148,10 +141,17 @@ function performupdate() {
         git submodule update --depth 1 --init --recursive
     fi
 
+
+    # Make sure that the auto updater only uses 1 core for compiling
+    proccount=$(grep -c '^processor' /proc/cpuinfo)
+    if [ "$AUTOUPDATER" == true ]; then
+        proccount=1
+    fi
+
     #Create build folder in case it doesn't exist
     mkdir -p ./build
     # Update cathook
-    pushd build && cmake .. && cmake --build . --target cathook -- -j$(nproc --all) || { echo -e "\033[1;31m \n \nFailed to compile cathook\n\033[0m"; exit 1; }
+    pushd build && cmake .. && cmake --build . --target cathook -- -j$proccount || { echo -e "\033[1;31m \n \nFailed to compile cathook\n\033[0m"; exit 1; }
     # Update data
     cwd="$(pwd)"
     cmake --build . --target data || { echo -e "\033[1;31m\nFailed to update /opt/cathook/data directory! Trying with root rights!\n\033[0m"; $SUDO bash -c "cd \"$cwd\"; cmake --build . --target data" || { echo -e "\033[1;31m\nFailed to update /opt/cathook/data directory\n\033[0m"; exit 1; } }
