xd

diff --git a/scripts/updater b/scripts/updater
--- a/scripts/updater
+++ b/scripts/updater
@@ -107,7 +107,7 @@ function performupdate() {
 
     if [ "$update_channel" == "master" ]; then
         git fetch --force --depth 1 origin && git reset --hard origin/master
- git fetch --force --depth 1 origin || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. https://github.com/ARandomlyGeneratedUsername/pastedhook\n\033[0m"; exit 1; } }
+ git fetch --force --depth 1 origin || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended.\n\033[0m"; exit 1; } }
     elif [ "$update_channel" == "developer" ]; then
         echo -e "\033[1;33mRunning in developer mode!\n\033[0m" && git pull origin --rebase=false || { echo -e "\033[1;31m\n\nFailed to pull from github!\n\033[0m"; exit 1; }
     else
